/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    questions: Question;
    ideologies: Ideology;
    politicians: Politician;
    countries: Country;
    results: Result;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    ideologies: IdeologiesSelect<false> | IdeologiesSelect<true>;
    politicians: PoliticiansSelect<false> | PoliticiansSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Beheerders met toegang tot het CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Politieke stellingen die in de quiz worden voorgelegd. Per dimensie moet er een gelijke balans zijn tussen 'positive' en 'negative' direction.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  /**
   * Concrete, actuele stelling. Vermijd vage platitudes; wees specifiek over beleid of waarde.
   */
  statement: string;
  dimension: 'economic' | 'social' | 'civil' | 'governance' | 'trust';
  /**
   * Bepaalt of 'volledig mee eens' de score richting de positieve of negatieve pool stuurt.
   */
  direction: 'positive' | 'negative';
  weight: number;
  /**
   * In welke quiz-lengtes verschijnt deze stelling? Quick is een subset van Standard, Standard van Extended.
   */
  tiers: ('quick' | 'standard' | 'extended')[];
  /**
   * Wordt getoond als de gebruiker op de info-knop tikt. Houd het neutraal en gebalanceerd.
   */
  info?: {
    context?: string | null;
    argumentsFor?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    argumentsAgainst?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Onderbouwende bronnen die de gekozen positie of stelling staven.
     */
    sources?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Politieke stromingen die als resultaat aan de gebruiker worden gepresenteerd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideologies".
 */
export interface Ideology {
  id: number;
  name: string;
  /**
   * Kebab-case identifier, bv. 'sociaal-democraat'.
   */
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  spectrumPosition: 'ver-links' | 'links' | 'centrum-links' | 'centrum' | 'centrum-rechts' | 'rechts' | 'ver-rechts';
  /**
   * Score per dimensie tussen -100 en +100. -100 = volledig negatieve pool, +100 = volledig positieve pool.
   */
  profileVector: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  examplePeople?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bekende politici die als referentiepunten dienen op de resultaatpagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicians".
 */
export interface Politician {
  id: number;
  name: string;
  role: string;
  country: string;
  party: string;
  isInternational?: boolean | null;
  bio: string;
  /**
   * Score per dimensie tussen -100 en +100. -100 = volledig negatieve pool, +100 = volledig positieve pool.
   */
  positionVector: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  /**
   * Onderbouwende bronnen die de gekozen positie of stelling staven.
   */
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Landen met hun gemiddelde politieke positie als referentie voor de gebruiker.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  countryCode: string;
  description: string;
  /**
   * Score per dimensie tussen -100 en +100. -100 = volledig negatieve pool, +100 = volledig positieve pool.
   */
  positionVector: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  /**
   * Onderbouwende bronnen die de gekozen positie of stelling staven.
   */
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anoniem opgeslagen quizresultaten, opgehaald via een shareId in de URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  /**
   * Korte unieke string in de URL.
   */
  shareId: string;
  lengthTier: 'quick' | 'standard' | 'extended';
  ideologySlug: string;
  dimensions: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  answeredCount: number;
  skippedCount: number;
  totalQuestions: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'ideologies';
        value: number | Ideology;
      } | null)
    | ({
        relationTo: 'politicians';
        value: number | Politician;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  statement?: T;
  dimension?: T;
  direction?: T;
  weight?: T;
  tiers?: T;
  info?:
    | T
    | {
        context?: T;
        argumentsFor?:
          | T
          | {
              text?: T;
              id?: T;
            };
        argumentsAgainst?:
          | T
          | {
              text?: T;
              id?: T;
            };
        sources?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideologies_select".
 */
export interface IdeologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  spectrumPosition?: T;
  profileVector?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  examplePeople?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicians_select".
 */
export interface PoliticiansSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  country?: T;
  party?: T;
  isInternational?: T;
  bio?: T;
  positionVector?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  countryCode?: T;
  description?: T;
  positionVector?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  shareId?: T;
  lengthTier?: T;
  ideologySlug?: T;
  dimensions?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  answeredCount?: T;
  skippedCount?: T;
  totalQuestions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}