/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const questions_themes = sqliteTable(
  "questions_themes",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: text("value", {
      enum: [
        "klimaat",
        "zorg",
        "migratie",
        "economie",
        "eu",
        "democratie",
        "wonen",
      ],
    }),
    id: integer("id").primaryKey(),
  },
  (columns) => [
    index("questions_themes_order_idx").on(columns.order),
    index("questions_themes_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [questions.id],
      name: "questions_themes_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const questions_tiers = sqliteTable(
  "questions_tiers",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: text("value", { enum: ["quick", "standard", "extended"] }),
    id: integer("id").primaryKey(),
  },
  (columns) => [
    index("questions_tiers_order_idx").on(columns.order),
    index("questions_tiers_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [questions.id],
      name: "questions_tiers_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const questions_info_arguments_for = sqliteTable(
  "questions_info_arguments_for",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    text: text("text").notNull(),
  },
  (columns) => [
    index("questions_info_arguments_for_order_idx").on(columns._order),
    index("questions_info_arguments_for_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [questions.id],
      name: "questions_info_arguments_for_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const questions_info_arguments_against = sqliteTable(
  "questions_info_arguments_against",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    text: text("text").notNull(),
  },
  (columns) => [
    index("questions_info_arguments_against_order_idx").on(columns._order),
    index("questions_info_arguments_against_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [questions.id],
      name: "questions_info_arguments_against_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const questions_info_sources = sqliteTable(
  "questions_info_sources",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("questions_info_sources_order_idx").on(columns._order),
    index("questions_info_sources_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [questions.id],
      name: "questions_info_sources_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const questions = sqliteTable(
  "questions",
  {
    id: integer("id").primaryKey(),
    statement: text("statement").notNull(),
    dimension: text("dimension", {
      enum: ["economic", "social", "civil", "governance", "trust"],
    }).notNull(),
    direction: text("direction", { enum: ["positive", "negative"] })
      .notNull()
      .default("positive"),
    weight: numeric("weight", { mode: "number" }).notNull().default(1),
    depth: text("depth", { enum: ["broad", "deep"] })
      .notNull()
      .default("broad"),
    discriminator: numeric("discriminator", { mode: "number" }).default(50),
    derivedStance: text("derived_stance"),
    info_context: text("info_context"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("questions_updated_at_idx").on(columns.updatedAt),
    index("questions_created_at_idx").on(columns.createdAt),
  ],
);

export const ideologies_example_people = sqliteTable(
  "ideologies_example_people",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    text: text("text").notNull(),
  },
  (columns) => [
    index("ideologies_example_people_order_idx").on(columns._order),
    index("ideologies_example_people_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [ideologies.id],
      name: "ideologies_example_people_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const ideologies = sqliteTable(
  "ideologies",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    shortDescription: text("short_description").notNull(),
    description: text("description", { mode: "json" }).notNull(),
    spectrumPosition: text("spectrum_position", {
      enum: [
        "ver-links",
        "links",
        "centrum-links",
        "centrum",
        "centrum-rechts",
        "rechts",
        "ver-rechts",
      ],
    }).notNull(),
    profileVector_economic: numeric("profile_vector_economic", {
      mode: "number",
    }).notNull(),
    profileVector_social: numeric("profile_vector_social", {
      mode: "number",
    }).notNull(),
    profileVector_civil: numeric("profile_vector_civil", {
      mode: "number",
    }).notNull(),
    profileVector_governance: numeric("profile_vector_governance", {
      mode: "number",
    }).notNull(),
    profileVector_trust: numeric("profile_vector_trust", {
      mode: "number",
    }).notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("ideologies_slug_idx").on(columns.slug),
    index("ideologies_updated_at_idx").on(columns.updatedAt),
    index("ideologies_created_at_idx").on(columns.createdAt),
  ],
);

export const politicians_quotes = sqliteTable(
  "politicians_quotes",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    text: text("text").notNull(),
    sourceLabel: text("source_label").notNull(),
    sourceUrl: text("source_url"),
  },
  (columns) => [
    index("politicians_quotes_order_idx").on(columns._order),
    index("politicians_quotes_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [politicians.id],
      name: "politicians_quotes_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const politicians_sources = sqliteTable(
  "politicians_sources",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("politicians_sources_order_idx").on(columns._order),
    index("politicians_sources_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [politicians.id],
      name: "politicians_sources_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const politicians = sqliteTable(
  "politicians",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    role: text("role").notNull(),
    roleKind: text("role_kind", {
      enum: [
        "minister-president",
        "vice-premier",
        "minister",
        "fractievoorzitter",
        "kamerlid",
        "partijleider",
        "europarlementarier",
        "president",
        "premier",
        "bondskanselier",
        "senator",
        "congreslid",
        "voormalig",
      ],
    }),
    country: text("country").notNull(),
    party: text("party").notNull(),
    partySlug: text("party_slug"),
    isInternational: integer("is_international", { mode: "boolean" }).default(
      false,
    ),
    bio: text("bio").notNull(),
    positionVector_economic: numeric("position_vector_economic", {
      mode: "number",
    }).notNull(),
    positionVector_social: numeric("position_vector_social", {
      mode: "number",
    }).notNull(),
    positionVector_civil: numeric("position_vector_civil", {
      mode: "number",
    }).notNull(),
    positionVector_governance: numeric("position_vector_governance", {
      mode: "number",
    }).notNull(),
    positionVector_trust: numeric("position_vector_trust", {
      mode: "number",
    }).notNull(),
    lastReviewed: text("last_reviewed").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("politicians_updated_at_idx").on(columns.updatedAt),
    index("politicians_created_at_idx").on(columns.createdAt),
  ],
);

export const politicians_texts = sqliteTable(
  "politicians_texts",
  {
    id: integer("id").primaryKey(),
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    text: text("text"),
  },
  (columns) => [
    index("politicians_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [politicians.id],
      name: "politicians_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const parties_sources = sqliteTable(
  "parties_sources",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("parties_sources_order_idx").on(columns._order),
    index("parties_sources_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [parties.id],
      name: "parties_sources_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const parties = sqliteTable(
  "parties",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    abbreviation: text("abbreviation").notNull(),
    slug: text("slug").notNull(),
    region: text("region", { enum: ["NL", "EU", "US"] }).notNull(),
    regionType: text("region_type", {
      enum: ["national", "family", "faction"],
    }).notNull(),
    country: text("country"),
    description: text("description", { mode: "json" }).notNull(),
    positionVector_economic: numeric("position_vector_economic", {
      mode: "number",
    }).notNull(),
    positionVector_social: numeric("position_vector_social", {
      mode: "number",
    }).notNull(),
    positionVector_civil: numeric("position_vector_civil", {
      mode: "number",
    }).notNull(),
    positionVector_governance: numeric("position_vector_governance", {
      mode: "number",
    }).notNull(),
    positionVector_trust: numeric("position_vector_trust", {
      mode: "number",
    }).notNull(),
    founded: text("founded"),
    leader: text("leader"),
    factionLeader: text("faction_leader"),
    websiteUrl: text("website_url"),
    seatsTK2025: numeric("seats_t_k2025", { mode: "number" }),
    coalitionStatus: text("coalition_status", {
      enum: ["governing", "opposition", "splinter", "none"],
    }),
    cpbReviewed2025: integer("cpb_reviewed2025", { mode: "boolean" }).default(
      false,
    ),
    lastReviewed: text("last_reviewed").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("parties_slug_idx").on(columns.slug),
    index("parties_updated_at_idx").on(columns.updatedAt),
    index("parties_created_at_idx").on(columns.createdAt),
  ],
);

export const parties_texts = sqliteTable(
  "parties_texts",
  {
    id: integer("id").primaryKey(),
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    text: text("text"),
  },
  (columns) => [
    index("parties_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [parties.id],
      name: "parties_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const countries_sources = sqliteTable(
  "countries_sources",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("countries_sources_order_idx").on(columns._order),
    index("countries_sources_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [countries.id],
      name: "countries_sources_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const countries = sqliteTable(
  "countries",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    countryCode: text("country_code").notNull(),
    description: text("description").notNull(),
    positionVector_economic: numeric("position_vector_economic", {
      mode: "number",
    }).notNull(),
    positionVector_social: numeric("position_vector_social", {
      mode: "number",
    }).notNull(),
    positionVector_civil: numeric("position_vector_civil", {
      mode: "number",
    }).notNull(),
    positionVector_governance: numeric("position_vector_governance", {
      mode: "number",
    }).notNull(),
    positionVector_trust: numeric("position_vector_trust", {
      mode: "number",
    }).notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("countries_updated_at_idx").on(columns.updatedAt),
    index("countries_created_at_idx").on(columns.createdAt),
  ],
);

export const results_paradoxes_example_question_ids = sqliteTable(
  "results_paradoxes_example_question_ids",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    questionId: numeric("question_id", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("results_paradoxes_example_question_ids_order_idx").on(
      columns._order,
    ),
    index("results_paradoxes_example_question_ids_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [results_paradoxes.id],
      name: "results_paradoxes_example_question_ids_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const results_paradoxes = sqliteTable(
  "results_paradoxes",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    dimension: text("dimension"),
    theme: text("theme"),
    type: text("type").notNull(),
    severity: numeric("severity", { mode: "number" }).notNull(),
    description: text("description"),
  },
  (columns) => [
    index("results_paradoxes_order_idx").on(columns._order),
    index("results_paradoxes_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [results.id],
      name: "results_paradoxes_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const results_answers = sqliteTable(
  "results_answers",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    questionId: numeric("question_id", { mode: "number" }).notNull(),
    value: numeric("value", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("results_answers_order_idx").on(columns._order),
    index("results_answers_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [results.id],
      name: "results_answers_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const results = sqliteTable(
  "results",
  {
    id: integer("id").primaryKey(),
    shareId: text("share_id").notNull(),
    lengthTier: text("length_tier", { enum: ["quick", "standard", "extended"] })
      .notNull()
      .default("standard"),
    ideologySlug: text("ideology_slug").notNull(),
    dimensions_economic: numeric("dimensions_economic", {
      mode: "number",
    }).notNull(),
    dimensions_social: numeric("dimensions_social", {
      mode: "number",
    }).notNull(),
    dimensions_civil: numeric("dimensions_civil", { mode: "number" }).notNull(),
    dimensions_governance: numeric("dimensions_governance", {
      mode: "number",
    }).notNull(),
    dimensions_trust: numeric("dimensions_trust", { mode: "number" }).notNull(),
    themeScores_klimaat: numeric("theme_scores_klimaat", { mode: "number" }),
    themeScores_zorg: numeric("theme_scores_zorg", { mode: "number" }),
    themeScores_migratie: numeric("theme_scores_migratie", { mode: "number" }),
    themeScores_economie: numeric("theme_scores_economie", { mode: "number" }),
    themeScores_eu: numeric("theme_scores_eu", { mode: "number" }),
    themeScores_democratie: numeric("theme_scores_democratie", {
      mode: "number",
    }),
    themeScores_wonen: numeric("theme_scores_wonen", { mode: "number" }),
    confidence_economic: numeric("confidence_economic", { mode: "number" }),
    confidence_social: numeric("confidence_social", { mode: "number" }),
    confidence_civil: numeric("confidence_civil", { mode: "number" }),
    confidence_governance: numeric("confidence_governance", { mode: "number" }),
    confidence_trust: numeric("confidence_trust", { mode: "number" }),
    answeredCount: numeric("answered_count", { mode: "number" }).notNull(),
    skippedCount: numeric("skipped_count", { mode: "number" }).notNull(),
    totalQuestions: numeric("total_questions", { mode: "number" }).notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("results_share_id_idx").on(columns.shareId),
    index("results_ideology_slug_idx").on(columns.ideologySlug),
    index("results_updated_at_idx").on(columns.updatedAt),
    index("results_created_at_idx").on(columns.createdAt),
  ],
);

export const ai_content_items = sqliteTable(
  "ai_content_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    text: text("text").notNull(),
    meta: text("meta"),
  },
  (columns) => [
    index("ai_content_items_order_idx").on(columns._order),
    index("ai_content_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [ai_content.id],
      name: "ai_content_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const ai_content = sqliteTable(
  "ai_content",
  {
    id: integer("id").primaryKey(),
    slug: text("slug").notNull(),
    kind: text("kind", {
      enum: [
        "ideology-essay",
        "ideology-reading",
        "ideology-arguments-for",
        "ideology-arguments-against",
        "ideology-theme",
        "dimension-bucket",
        "paradox",
      ],
    }).notNull(),
    title: text("title"),
    body: text("body", { mode: "json" }).notNull(),
    model: text("model").notNull(),
    generatedAt: text("generated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    prompt: text("prompt"),
    humanEdited: integer("human_edited", { mode: "boolean" }).default(false),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("ai_content_slug_idx").on(columns.slug),
    index("ai_content_updated_at_idx").on(columns.updatedAt),
    index("ai_content_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
    questionsID: integer("questions_id"),
    ideologiesID: integer("ideologies_id"),
    politiciansID: integer("politicians_id"),
    partiesID: integer("parties_id"),
    countriesID: integer("countries_id"),
    resultsID: integer("results_id"),
    aiContentID: integer("ai_content_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_questions_id_idx").on(
      columns.questionsID,
    ),
    index("payload_locked_documents_rels_ideologies_id_idx").on(
      columns.ideologiesID,
    ),
    index("payload_locked_documents_rels_politicians_id_idx").on(
      columns.politiciansID,
    ),
    index("payload_locked_documents_rels_parties_id_idx").on(columns.partiesID),
    index("payload_locked_documents_rels_countries_id_idx").on(
      columns.countriesID,
    ),
    index("payload_locked_documents_rels_results_id_idx").on(columns.resultsID),
    index("payload_locked_documents_rels_ai_content_id_idx").on(
      columns.aiContentID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["questionsID"]],
      foreignColumns: [questions.id],
      name: "payload_locked_documents_rels_questions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["ideologiesID"]],
      foreignColumns: [ideologies.id],
      name: "payload_locked_documents_rels_ideologies_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["politiciansID"]],
      foreignColumns: [politicians.id],
      name: "payload_locked_documents_rels_politicians_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["partiesID"]],
      foreignColumns: [parties.id],
      name: "payload_locked_documents_rels_parties_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["countriesID"]],
      foreignColumns: [countries.id],
      name: "payload_locked_documents_rels_countries_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["resultsID"]],
      foreignColumns: [results.id],
      name: "payload_locked_documents_rels_results_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["aiContentID"]],
      foreignColumns: [ai_content.id],
      name: "payload_locked_documents_rels_ai_content_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_questions_themes = relations(
  questions_themes,
  ({ one }) => ({
    parent: one(questions, {
      fields: [questions_themes.parent],
      references: [questions.id],
      relationName: "themes",
    }),
  }),
);
export const relations_questions_tiers = relations(
  questions_tiers,
  ({ one }) => ({
    parent: one(questions, {
      fields: [questions_tiers.parent],
      references: [questions.id],
      relationName: "tiers",
    }),
  }),
);
export const relations_questions_info_arguments_for = relations(
  questions_info_arguments_for,
  ({ one }) => ({
    _parentID: one(questions, {
      fields: [questions_info_arguments_for._parentID],
      references: [questions.id],
      relationName: "info_argumentsFor",
    }),
  }),
);
export const relations_questions_info_arguments_against = relations(
  questions_info_arguments_against,
  ({ one }) => ({
    _parentID: one(questions, {
      fields: [questions_info_arguments_against._parentID],
      references: [questions.id],
      relationName: "info_argumentsAgainst",
    }),
  }),
);
export const relations_questions_info_sources = relations(
  questions_info_sources,
  ({ one }) => ({
    _parentID: one(questions, {
      fields: [questions_info_sources._parentID],
      references: [questions.id],
      relationName: "info_sources",
    }),
  }),
);
export const relations_questions = relations(questions, ({ many }) => ({
  themes: many(questions_themes, {
    relationName: "themes",
  }),
  tiers: many(questions_tiers, {
    relationName: "tiers",
  }),
  info_argumentsFor: many(questions_info_arguments_for, {
    relationName: "info_argumentsFor",
  }),
  info_argumentsAgainst: many(questions_info_arguments_against, {
    relationName: "info_argumentsAgainst",
  }),
  info_sources: many(questions_info_sources, {
    relationName: "info_sources",
  }),
}));
export const relations_ideologies_example_people = relations(
  ideologies_example_people,
  ({ one }) => ({
    _parentID: one(ideologies, {
      fields: [ideologies_example_people._parentID],
      references: [ideologies.id],
      relationName: "examplePeople",
    }),
  }),
);
export const relations_ideologies = relations(ideologies, ({ many }) => ({
  examplePeople: many(ideologies_example_people, {
    relationName: "examplePeople",
  }),
}));
export const relations_politicians_quotes = relations(
  politicians_quotes,
  ({ one }) => ({
    _parentID: one(politicians, {
      fields: [politicians_quotes._parentID],
      references: [politicians.id],
      relationName: "quotes",
    }),
  }),
);
export const relations_politicians_sources = relations(
  politicians_sources,
  ({ one }) => ({
    _parentID: one(politicians, {
      fields: [politicians_sources._parentID],
      references: [politicians.id],
      relationName: "sources",
    }),
  }),
);
export const relations_politicians_texts = relations(
  politicians_texts,
  ({ one }) => ({
    parent: one(politicians, {
      fields: [politicians_texts.parent],
      references: [politicians.id],
      relationName: "_texts",
    }),
  }),
);
export const relations_politicians = relations(politicians, ({ many }) => ({
  quotes: many(politicians_quotes, {
    relationName: "quotes",
  }),
  sources: many(politicians_sources, {
    relationName: "sources",
  }),
  _texts: many(politicians_texts, {
    relationName: "_texts",
  }),
}));
export const relations_parties_sources = relations(
  parties_sources,
  ({ one }) => ({
    _parentID: one(parties, {
      fields: [parties_sources._parentID],
      references: [parties.id],
      relationName: "sources",
    }),
  }),
);
export const relations_parties_texts = relations(parties_texts, ({ one }) => ({
  parent: one(parties, {
    fields: [parties_texts.parent],
    references: [parties.id],
    relationName: "_texts",
  }),
}));
export const relations_parties = relations(parties, ({ many }) => ({
  sources: many(parties_sources, {
    relationName: "sources",
  }),
  _texts: many(parties_texts, {
    relationName: "_texts",
  }),
}));
export const relations_countries_sources = relations(
  countries_sources,
  ({ one }) => ({
    _parentID: one(countries, {
      fields: [countries_sources._parentID],
      references: [countries.id],
      relationName: "sources",
    }),
  }),
);
export const relations_countries = relations(countries, ({ many }) => ({
  sources: many(countries_sources, {
    relationName: "sources",
  }),
}));
export const relations_results_paradoxes_example_question_ids = relations(
  results_paradoxes_example_question_ids,
  ({ one }) => ({
    _parentID: one(results_paradoxes, {
      fields: [results_paradoxes_example_question_ids._parentID],
      references: [results_paradoxes.id],
      relationName: "exampleQuestionIds",
    }),
  }),
);
export const relations_results_paradoxes = relations(
  results_paradoxes,
  ({ one, many }) => ({
    _parentID: one(results, {
      fields: [results_paradoxes._parentID],
      references: [results.id],
      relationName: "paradoxes",
    }),
    exampleQuestionIds: many(results_paradoxes_example_question_ids, {
      relationName: "exampleQuestionIds",
    }),
  }),
);
export const relations_results_answers = relations(
  results_answers,
  ({ one }) => ({
    _parentID: one(results, {
      fields: [results_answers._parentID],
      references: [results.id],
      relationName: "answers",
    }),
  }),
);
export const relations_results = relations(results, ({ many }) => ({
  paradoxes: many(results_paradoxes, {
    relationName: "paradoxes",
  }),
  answers: many(results_answers, {
    relationName: "answers",
  }),
}));
export const relations_ai_content_items = relations(
  ai_content_items,
  ({ one }) => ({
    _parentID: one(ai_content, {
      fields: [ai_content_items._parentID],
      references: [ai_content.id],
      relationName: "items",
    }),
  }),
);
export const relations_ai_content = relations(ai_content, ({ many }) => ({
  items: many(ai_content_items, {
    relationName: "items",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    questionsID: one(questions, {
      fields: [payload_locked_documents_rels.questionsID],
      references: [questions.id],
      relationName: "questions",
    }),
    ideologiesID: one(ideologies, {
      fields: [payload_locked_documents_rels.ideologiesID],
      references: [ideologies.id],
      relationName: "ideologies",
    }),
    politiciansID: one(politicians, {
      fields: [payload_locked_documents_rels.politiciansID],
      references: [politicians.id],
      relationName: "politicians",
    }),
    partiesID: one(parties, {
      fields: [payload_locked_documents_rels.partiesID],
      references: [parties.id],
      relationName: "parties",
    }),
    countriesID: one(countries, {
      fields: [payload_locked_documents_rels.countriesID],
      references: [countries.id],
      relationName: "countries",
    }),
    resultsID: one(results, {
      fields: [payload_locked_documents_rels.resultsID],
      references: [results.id],
      relationName: "results",
    }),
    aiContentID: one(ai_content, {
      fields: [payload_locked_documents_rels.aiContentID],
      references: [ai_content.id],
      relationName: "aiContent",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  questions_themes: typeof questions_themes;
  questions_tiers: typeof questions_tiers;
  questions_info_arguments_for: typeof questions_info_arguments_for;
  questions_info_arguments_against: typeof questions_info_arguments_against;
  questions_info_sources: typeof questions_info_sources;
  questions: typeof questions;
  ideologies_example_people: typeof ideologies_example_people;
  ideologies: typeof ideologies;
  politicians_quotes: typeof politicians_quotes;
  politicians_sources: typeof politicians_sources;
  politicians: typeof politicians;
  politicians_texts: typeof politicians_texts;
  parties_sources: typeof parties_sources;
  parties: typeof parties;
  parties_texts: typeof parties_texts;
  countries_sources: typeof countries_sources;
  countries: typeof countries;
  results_paradoxes_example_question_ids: typeof results_paradoxes_example_question_ids;
  results_paradoxes: typeof results_paradoxes;
  results_answers: typeof results_answers;
  results: typeof results;
  ai_content_items: typeof ai_content_items;
  ai_content: typeof ai_content;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_questions_themes: typeof relations_questions_themes;
  relations_questions_tiers: typeof relations_questions_tiers;
  relations_questions_info_arguments_for: typeof relations_questions_info_arguments_for;
  relations_questions_info_arguments_against: typeof relations_questions_info_arguments_against;
  relations_questions_info_sources: typeof relations_questions_info_sources;
  relations_questions: typeof relations_questions;
  relations_ideologies_example_people: typeof relations_ideologies_example_people;
  relations_ideologies: typeof relations_ideologies;
  relations_politicians_quotes: typeof relations_politicians_quotes;
  relations_politicians_sources: typeof relations_politicians_sources;
  relations_politicians_texts: typeof relations_politicians_texts;
  relations_politicians: typeof relations_politicians;
  relations_parties_sources: typeof relations_parties_sources;
  relations_parties_texts: typeof relations_parties_texts;
  relations_parties: typeof relations_parties;
  relations_countries_sources: typeof relations_countries_sources;
  relations_countries: typeof relations_countries;
  relations_results_paradoxes_example_question_ids: typeof relations_results_paradoxes_example_question_ids;
  relations_results_paradoxes: typeof relations_results_paradoxes;
  relations_results_answers: typeof relations_results_answers;
  relations_results: typeof relations_results;
  relations_ai_content_items: typeof relations_ai_content_items;
  relations_ai_content: typeof relations_ai_content;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
