/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    questions: Question;
    ideologies: Ideology;
    politicians: Politician;
    parties: Party;
    countries: Country;
    results: Result;
    aiContent: AiContent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    ideologies: IdeologiesSelect<false> | IdeologiesSelect<true>;
    politicians: PoliticiansSelect<false> | PoliticiansSelect<true>;
    parties: PartiesSelect<false> | PartiesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    aiContent: AiContentSelect<false> | AiContentSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Beheerders met toegang tot het CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Politieke stellingen die in de quiz worden voorgelegd. Per dimensie moet er een gelijke balans zijn tussen 'positive' en 'negative' direction.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  /**
   * Concrete, actuele stelling. Vermijd vage platitudes; wees specifiek over beleid of waarde.
   */
  statement: string;
  dimension: 'economic' | 'social' | 'civil' | 'governance' | 'trust';
  /**
   * Bepaalt of 'volledig mee eens' de score richting de positieve of negatieve pool stuurt.
   */
  direction: 'positive' | 'negative';
  weight: number;
  /**
   * Broad = kalibratievraag, breed onderscheidend; deep = verdiepingsvraag voor nuance.
   */
  depth: 'broad' | 'deep';
  /**
   * 0-100. Hoe sterk deze vraag tussen ideologie-clusters onderscheidt; gebruikt door de adaptieve engine.
   */
  discriminator?: number | null;
  /**
   * Eén of meer thema-tags. Stellingen zonder thema tellen alleen mee voor de hoofd-dimensies.
   */
  themes?: ('klimaat' | 'zorg' | 'migratie' | 'economie' | 'eu' | 'democratie' | 'wonen')[] | null;
  /**
   * Voorgeformuleerd standpunt dat we tonen op de resultaatpagina ALS de gebruiker (sterk) eens is met deze stelling. Bv. 'Jij vindt dat de hoogste inkomens zwaarder belast moeten worden.'
   */
  derivedStance?: string | null;
  /**
   * In welke quiz-lengtes verschijnt deze stelling? Quick is een subset van Standard, Standard van Extended.
   */
  tiers: ('quick' | 'standard' | 'extended')[];
  /**
   * Wordt getoond als de gebruiker op de info-knop tikt. Houd het neutraal en gebalanceerd.
   */
  info?: {
    context?: string | null;
    argumentsFor?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    argumentsAgainst?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Onderbouwende bronnen die de gekozen positie of stelling staven.
     */
    sources?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Politieke stromingen die als resultaat aan de gebruiker worden gepresenteerd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideologies".
 */
export interface Ideology {
  id: number;
  name: string;
  /**
   * Kebab-case identifier, bv. 'sociaal-democraat'.
   */
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  spectrumPosition: 'ver-links' | 'links' | 'centrum-links' | 'centrum' | 'centrum-rechts' | 'rechts' | 'ver-rechts';
  /**
   * Score per dimensie tussen -100 en +100. -100 = volledig negatieve pool, +100 = volledig positieve pool.
   */
  profileVector: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  examplePeople?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bekende politici die als referentiepunten dienen op de resultaatpagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicians".
 */
export interface Politician {
  id: number;
  name: string;
  role: string;
  roleKind?:
    | (
        | 'minister-president'
        | 'vice-premier'
        | 'minister'
        | 'fractievoorzitter'
        | 'kamerlid'
        | 'partijleider'
        | 'europarlementarier'
        | 'president'
        | 'premier'
        | 'bondskanselier'
        | 'senator'
        | 'congreslid'
        | 'voormalig'
      )
    | null;
  country: string;
  party: string;
  /**
   * Kebab-case slug van de gerelateerde partij in `parties` (bv. 'd66').
   */
  partySlug?: string | null;
  isInternational?: boolean | null;
  bio: string;
  /**
   * Eén of meer ideologie-slugs (bv. 'sociaal-liberaal') waarop deze politicus politiek het meeste lijkt. Wordt gebruikt voor de 'politici van jouw ideologie'-toggle.
   */
  ideologySlugs?: string[] | null;
  /**
   * Score per dimensie tussen -100 en +100. -100 = volledig negatieve pool, +100 = volledig positieve pool.
   */
  positionVector: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  /**
   * Pakkende quotes voor onder andere de Turing-test en politicus-detailpagina.
   */
  quotes?:
    | {
        text: string;
        sourceLabel: string;
        sourceUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Datum van laatste verificatie van rol en positie. Politici wisselen partij of rol; dit is de peildatum per build.
   */
  lastReviewed?: string | null;
  /**
   * Onderbouwende bronnen die de gekozen positie of stelling staven.
   */
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Politieke partijen en partij-families als educatieve context per ideologie. NIET als persoonlijke ranking voor de gebruiker.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parties".
 */
export interface Party {
  id: number;
  name: string;
  abbreviation: string;
  /**
   * Kebab-case identifier, bv. 'pvv' of 'epp'.
   */
  slug: string;
  region: 'NL' | 'EU' | 'US';
  regionType: 'national' | 'family' | 'faction';
  country?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Eén of meer ideologie-slugs (bv. 'sociaal-democraat') waarop deze partij politiek het meeste lijkt. Wordt gebruikt om partijen in de resultaatpagina te koppelen aan de ideologie van de gebruiker.
   */
  ideologySlugs: string[];
  /**
   * Score per dimensie tussen -100 en +100. -100 = volledig negatieve pool, +100 = volledig positieve pool.
   */
  positionVector: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  founded?: string | null;
  leader?: string | null;
  factionLeader?: string | null;
  websiteUrl?: string | null;
  /**
   * Aantal Tweede Kamer-zetels na verkiezingen 29 oktober 2025, inclusief eventuele afsplitsingen per peildatum.
   */
  seatsTK2025?: number | null;
  coalitionStatus?: ('governing' | 'opposition' | 'splinter' | 'none') | null;
  cpbReviewed2025?: boolean | null;
  /**
   * Wanneer is deze partij-positie voor het laatst gecontroleerd? Eens per jaar herzien.
   */
  lastReviewed?: string | null;
  /**
   * Onderbouwende bronnen die de gekozen positie of stelling staven.
   */
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Landen met hun gemiddelde politieke positie als referentie voor de gebruiker.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  countryCode: string;
  description: string;
  /**
   * Score per dimensie tussen -100 en +100. -100 = volledig negatieve pool, +100 = volledig positieve pool.
   */
  positionVector: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  /**
   * Onderbouwende bronnen die de gekozen positie of stelling staven.
   */
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anoniem opgeslagen quizresultaten, opgehaald via een shareId in de URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  /**
   * Korte unieke string in de URL.
   */
  shareId: string;
  lengthTier: 'quick' | 'standard' | 'extended';
  ideologySlug: string;
  dimensions: {
    economic: number;
    social: number;
    civil: number;
    governance: number;
    trust: number;
  };
  /**
   * Optioneel; pas gevuld vanaf v2 van de quiz. Score per thema -100..+100.
   */
  themeScores?: {
    klimaat?: number | null;
    zorg?: number | null;
    migratie?: number | null;
    economie?: number | null;
    eu?: number | null;
    democratie?: number | null;
    wonen?: number | null;
  };
  /**
   * Optioneel; pas gevuld vanaf v2. Hoe zeker het profiel is per dimensie, op basis van # antwoorden, sterkte en variance.
   */
  confidence?: {
    economic?: number | null;
    social?: number | null;
    civil?: number | null;
    governance?: number | null;
    trust?: number | null;
  };
  /**
   * Lijst van interne tegenstrijdigheden gedetecteerd in de antwoorden.
   */
  paradoxes?:
    | {
        dimension?: string | null;
        theme?: string | null;
        type: string;
        severity: number;
        description?: string | null;
        exampleQuestionIds?:
          | {
              questionId: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Vraag-ID + waarde voor stance-extractie. Bevat geen PII.
   */
  answers?:
    | {
        questionId: number;
        value: number;
        id?: string | null;
      }[]
    | null;
  answeredCount: number;
  skippedCount: number;
  totalQuestions: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vooraf gegenereerde teksten voor de resultaatpagina. Build-time gegenereerd, gebruiker-data raakt nooit OpenAI.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aiContent".
 */
export interface AiContent {
  id: number;
  /**
   * Unieke sleutel, bv. 'ideology:sociaal-liberaal:essay' of 'dimension:economic:bucket:strong-positive'.
   */
  slug: string;
  kind:
    | 'ideology-essay'
    | 'ideology-reading'
    | 'ideology-arguments-for'
    | 'ideology-arguments-against'
    | 'ideology-theme'
    | 'dimension-bucket'
    | 'paradox';
  title?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optioneel: voor slots die uit een reeks korte items bestaan (bv. argumentsFor, reading).
   */
  items?:
    | {
        text: string;
        meta?: string | null;
        /**
         * Externe URL naar boek/artikel (bv. bol.com product-pagina of bibliotheek-record).
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bv. 'gpt-4o-2024-08-06'.
   */
  model: string;
  generatedAt: string;
  /**
   * Volledige prompt waarmee deze tekst is gegenereerd. Openbaar voor transparantie.
   */
  prompt?: string | null;
  /**
   * Aanvinken als een redacteur deze tekst heeft aangepast; voorkomt overschrijven bij regeneratie.
   */
  humanEdited?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'ideologies';
        value: number | Ideology;
      } | null)
    | ({
        relationTo: 'politicians';
        value: number | Politician;
      } | null)
    | ({
        relationTo: 'parties';
        value: number | Party;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null)
    | ({
        relationTo: 'aiContent';
        value: number | AiContent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  statement?: T;
  dimension?: T;
  direction?: T;
  weight?: T;
  depth?: T;
  discriminator?: T;
  themes?: T;
  derivedStance?: T;
  tiers?: T;
  info?:
    | T
    | {
        context?: T;
        argumentsFor?:
          | T
          | {
              text?: T;
              id?: T;
            };
        argumentsAgainst?:
          | T
          | {
              text?: T;
              id?: T;
            };
        sources?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideologies_select".
 */
export interface IdeologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  spectrumPosition?: T;
  profileVector?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  examplePeople?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicians_select".
 */
export interface PoliticiansSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  roleKind?: T;
  country?: T;
  party?: T;
  partySlug?: T;
  isInternational?: T;
  bio?: T;
  ideologySlugs?: T;
  positionVector?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  quotes?:
    | T
    | {
        text?: T;
        sourceLabel?: T;
        sourceUrl?: T;
        id?: T;
      };
  lastReviewed?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parties_select".
 */
export interface PartiesSelect<T extends boolean = true> {
  name?: T;
  abbreviation?: T;
  slug?: T;
  region?: T;
  regionType?: T;
  country?: T;
  description?: T;
  ideologySlugs?: T;
  positionVector?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  founded?: T;
  leader?: T;
  factionLeader?: T;
  websiteUrl?: T;
  seatsTK2025?: T;
  coalitionStatus?: T;
  cpbReviewed2025?: T;
  lastReviewed?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  countryCode?: T;
  description?: T;
  positionVector?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  shareId?: T;
  lengthTier?: T;
  ideologySlug?: T;
  dimensions?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  themeScores?:
    | T
    | {
        klimaat?: T;
        zorg?: T;
        migratie?: T;
        economie?: T;
        eu?: T;
        democratie?: T;
        wonen?: T;
      };
  confidence?:
    | T
    | {
        economic?: T;
        social?: T;
        civil?: T;
        governance?: T;
        trust?: T;
      };
  paradoxes?:
    | T
    | {
        dimension?: T;
        theme?: T;
        type?: T;
        severity?: T;
        description?: T;
        exampleQuestionIds?:
          | T
          | {
              questionId?: T;
              id?: T;
            };
        id?: T;
      };
  answers?:
    | T
    | {
        questionId?: T;
        value?: T;
        id?: T;
      };
  answeredCount?: T;
  skippedCount?: T;
  totalQuestions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aiContent_select".
 */
export interface AiContentSelect<T extends boolean = true> {
  slug?: T;
  kind?: T;
  title?: T;
  body?: T;
  items?:
    | T
    | {
        text?: T;
        meta?: T;
        link?: T;
        id?: T;
      };
  model?: T;
  generatedAt?: T;
  prompt?: T;
  humanEdited?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}